### ISSUE TITLE
Nic tady není

### ISSUE THREAD

**Issue by matyas-zavora** [NeDDy3z/jecna-pv-maturita#1]
Bludimír zapomněl přidat ty otázky 💀

**Comment by matyas-zavora** [comment]
<img src="https://i.pinimg.com/originals/81/94/e5/8194e5b25833fa2adf8251aeeeb720d0.gif">

**Comment by NeDDy3z** [comment]
:(

**Comment by matyas-zavora** [comment]
Už to tady je. Díky
